import type { ProviderConfig } from "@/types";

export const PROVIDERS: ProviderConfig[] = [
  {
    id: "claude",
    name: "Claude",
    description: "Anthropic's most capable AI models",
    requiresApiKey: true,
    keyPlaceholder: "sk-ant-api03-...",
    keyLink: "https://console.anthropic.com/settings/keys",
    keyLinkLabel: "console.anthropic.com",
    color: "text-amber-400",
    bgColor: "bg-amber-500/10",
    borderColor: "border-amber-500/20",
    activeBg: "bg-amber-500/20 border-amber-500/40",
    models: [
      { id: "claude-sonnet-4-20250514", name: "Claude Sonnet 4", desc: "Best balance of speed & intelligence" },
      { id: "claude-opus-4-20250514", name: "Claude Opus 4", desc: "Most capable for complex tasks" },
      { id: "claude-3-5-haiku-20241022", name: "Claude 3.5 Haiku", desc: "Fastest for simple tasks" },
    ],
  },
  {
    id: "openai",
    name: "OpenAI",
    description: "GPT-4o, o1, and more from OpenAI",
    requiresApiKey: true,
    keyPlaceholder: "sk-proj-...",
    keyLink: "https://platform.openai.com/api-keys",
    keyLinkLabel: "platform.openai.com",
    color: "text-green-400",
    bgColor: "bg-green-500/10",
    borderColor: "border-green-500/20",
    activeBg: "bg-green-500/20 border-green-500/40",
    models: [
      { id: "gpt-4o", name: "GPT-4o", desc: "Most capable multimodal model" },
      { id: "gpt-4o-mini", name: "GPT-4o Mini", desc: "Fast and affordable" },
      { id: "o1", name: "o1", desc: "Advanced reasoning model" },
      { id: "o1-mini", name: "o1 Mini", desc: "Fast reasoning model" },
    ],
  },
  {
    id: "gemini",
    name: "Gemini",
    description: "Google's multimodal AI models",
    requiresApiKey: true,
    keyPlaceholder: "AIza...",
    keyLink: "https://aistudio.google.com/app/apikey",
    keyLinkLabel: "aistudio.google.com",
    color: "text-blue-400",
    bgColor: "bg-blue-500/10",
    borderColor: "border-blue-500/20",
    activeBg: "bg-blue-500/20 border-blue-500/40",
    models: [
      { id: "gemini-2.0-flash", name: "Gemini 2.0 Flash", desc: "Fast and efficient" },
      { id: "gemini-2.5-pro-preview-06-05", name: "Gemini 2.5 Pro", desc: "Most capable Gemini" },
      { id: "gemini-2.0-flash-lite", name: "Gemini 2.0 Flash Lite", desc: "Ultra-fast responses" },
    ],
  },
  {
    id: "groq",
    name: "Groq",
    description: "Ultra-fast inference on LPU hardware",
    requiresApiKey: true,
    keyPlaceholder: "gsk_...",
    keyLink: "https://console.groq.com/keys",
    keyLinkLabel: "console.groq.com",
    color: "text-orange-400",
    bgColor: "bg-orange-500/10",
    borderColor: "border-orange-500/20",
    activeBg: "bg-orange-500/20 border-orange-500/40",
    models: [
      { id: "llama-3.3-70b-versatile", name: "Llama 3.3 70B", desc: "Meta's latest open model" },
      { id: "mixtral-8x7b-32768", name: "Mixtral 8x7B", desc: "Mistral's mixture of experts" },
      { id: "gemma2-9b-it", name: "Gemma 2 9B", desc: "Google's compact model" },
    ],
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    description: "Advanced reasoning and coding models",
    requiresApiKey: true,
    keyPlaceholder: "sk-...",
    keyLink: "https://platform.deepseek.com/api_keys",
    keyLinkLabel: "platform.deepseek.com",
    color: "text-cyan-400",
    bgColor: "bg-cyan-500/10",
    borderColor: "border-cyan-500/20",
    activeBg: "bg-cyan-500/20 border-cyan-500/40",
    models: [
      { id: "deepseek-chat", name: "DeepSeek Chat", desc: "General conversation" },
      { id: "deepseek-reasoner", name: "DeepSeek R1", desc: "Advanced reasoning" },
    ],
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    description: "Access 100+ models through one API",
    requiresApiKey: true,
    keyPlaceholder: "sk-or-...",
    keyLink: "https://openrouter.ai/keys",
    keyLinkLabel: "openrouter.ai",
    color: "text-purple-400",
    bgColor: "bg-purple-500/10",
    borderColor: "border-purple-500/20",
    activeBg: "bg-purple-500/20 border-purple-500/40",
    models: [
      { id: "anthropic/claude-sonnet-4-20250514", name: "Claude Sonnet 4", desc: "Via OpenRouter" },
      { id: "openai/gpt-4o", name: "GPT-4o", desc: "Via OpenRouter" },
      { id: "google/gemini-2.0-flash-001", name: "Gemini Flash", desc: "Via OpenRouter" },
      { id: "meta-llama/llama-3.3-70b-instruct", name: "Llama 3.3 70B", desc: "Via OpenRouter" },
    ],
  },
  {
    id: "ollama",
    name: "Ollama",
    description: "Run models locally — no API key needed",
    requiresApiKey: false,
    defaultEndpoint: "http://localhost:11434",
    endpointEditable: true,
    color: "text-emerald-400",
    bgColor: "bg-emerald-500/10",
    borderColor: "border-emerald-500/20",
    activeBg: "bg-emerald-500/20 border-emerald-500/40",
    models: [
      { id: "llama3.2", name: "Llama 3.2", desc: "Meta's latest open model" },
      { id: "mistral", name: "Mistral 7B", desc: "Fast and efficient" },
      { id: "gemma2", name: "Gemma 2", desc: "Google's open model" },
      { id: "phi4", name: "Phi-4", desc: "Microsoft's compact model" },
      { id: "qwen2.5", name: "Qwen 2.5", desc: "Alibaba's open model" },
      { id: "deepseek-r1", name: "DeepSeek R1", desc: "Reasoning model" },
      { id: "codellama", name: "Code Llama", desc: "Optimized for code" },
    ],
  },
  {
    id: "lmstudio",
    name: "LM Studio",
    description: "Run models locally via LM Studio",
    requiresApiKey: false,
    defaultEndpoint: "http://localhost:1234",
    endpointEditable: true,
    color: "text-pink-400",
    bgColor: "bg-pink-500/10",
    borderColor: "border-pink-500/20",
    activeBg: "bg-pink-500/20 border-pink-500/40",
    models: [
      { id: "default", name: "Loaded Model", desc: "Currently loaded in LM Studio" },
    ],
  },
  {
    id: "custom",
    name: "Custom",
    description: "Any OpenAI-compatible endpoint",
    requiresApiKey: false,
    endpointEditable: true,
    color: "text-slate-400",
    bgColor: "bg-slate-500/10",
    borderColor: "border-slate-500/20",
    activeBg: "bg-slate-500/20 border-slate-500/40",
    models: [],
  },
];

export function getProviderConfig(id: string): ProviderConfig {
  return PROVIDERS.find((p) => p.id === id) || PROVIDERS[0];
}
